services:
  drone:
    image: drone/drone:2
    container_name: drone
    env_file:
      - .drone-env
    environment:
      - DRONE_GITHUB_CLIENT_ID=46989113bdad4f0ddbe7
      - DRONE_SERVER_HOST=drone.rnzaou.me
      - DRONE_SERVER_PROTO=https
      - DRONE_REGISTRATION_CLOSED=true
      - DRONE_COOKIE_TIMEOUT=72h
      - DRONE_LOGSCOLOR=true
    restart: always
    networks:
      - reverse-proxy
      - internal
    expose:
      - 80/tcp
    volumes:
      - drone-data:/data
  docker-runner:
    image: drone/drone-runner-docker:1
    container_name: docker-runner
    env_file:
      - .docker-runner-env
    environment:
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_PORT=80
      - DRONE_LIMIT_REPOS=rnza0u/*
      - DRONE_LIMIT_TRUSTED=true
      - DRONE_RUNNER_CAPACITY=2
    expose:
      - "3000"
    networks:
      - internal
    restart: always
    volumes:
      - /run/user/1002/docker.sock:/var/run/docker.sock
networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  internal:
    name: drone-internal
volumes:
  drone-data: {}